#!/usr/bin/env python3
"""Builds the MAME 2010 arcade ROM-doctor assets from src/metadata/mame2010.xml (MAME 0.139 -listxml dump
shipped in libretro/mame2010-libretro):

  assets/romdb.tsv.gz  — same schema as cores/mame2003plus/assets/romdb.tsv.gz (read by library/ArcadeRomCheck.kt)
  assets/titles.tsv    — name  description  year  manufacturer (read by library/ArcadeTitles.kt)

Usage: python3 gen-romdb.py  (run from anywhere; paths are relative to this script)

romdb columns (tab separated), one line per <game>:
  name  description  cloneof  romof  bios  sampleof  needsSamples  disks  runnable  roms
  - bios: the BIOS set zip (e.g. "neogeo", "psarc95") found by following the romof chain; "" if none.
  - sampleof: zip under <system>/mame2010/samples/ this game loads samples from ("" if none).
  - needsSamples: 1 when the game lists <sample> entries (optional; sound is incomplete without them).
  - disks: number of <disk> (CHD) entries. MAME 2010 does support CHDs (they go in <romdir>/<game>/<disk>.chd);
    the checker only reports the count.
  - runnable: 0 for BIOS sets (isbios="yes" — 0.139 does not emit runnable="no"), 1 otherwise.
  - roms: ';'-separated tokens "name:size:crc[:merge[:bios]]"
      merge = "" own file, "=" merged from the romof set under the same name, else the file name in the romof set.
      bios  = <biosset> name this file belongs to ("" for normal files); only one bios file per game is needed.
    <rom> entries without a crc (status="nodump") and optional="yes" entries are omitted — MAME does not require them.
Lines starting with '#' are comments.
"""
import gzip
import os
import sys
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "src", "metadata", "mame2010.xml")
OUT = os.path.join(HERE, "assets", "romdb.tsv.gz")
TITLES = os.path.join(HERE, "assets", "titles.tsv")
MAX_BYTES = 3 * 1024 * 1024


def esc(s: str) -> str:
    """Rom tokens use ':' and ';' as separators; escape them (MAME names practically never contain them)."""
    return s.replace("%", "%25").replace(":", "%3A").replace(";", "%3B")


def clean(s: str) -> str:
    return (s or "").replace("\t", " ").replace("\n", " ").strip()


def main() -> int:
    if not os.path.isfile(SRC):
        print(f"missing {SRC}: clone libretro/mame2010-libretro into cores/mame2010/src first", file=sys.stderr)
        return 2
    games = {}
    order = []
    skipped_optional = 0
    for _, el in ET.iterparse(SRC, events=("end",)):
        if el.tag != "game":
            continue
        name = el.get("name")
        roms = []
        for r in el.findall("rom"):
            crc = (r.get("crc") or "").lower()
            if not crc:
                continue  # nodump: not required
            if r.get("optional") == "yes":
                skipped_optional += 1
                continue
            rname = r.get("name") or ""
            merge = r.get("merge")
            if merge is None:
                mcol = ""
            elif merge == rname:
                mcol = "="
            else:
                mcol = esc(merge)
            bios = r.get("bios") or ""
            tok = f"{esc(rname)}:{int(r.get('size') or 0)}:{crc}"
            if mcol or bios:
                tok += f":{mcol}"
            if bios:
                tok += f":{esc(bios)}"
            roms.append(tok)
        samples = el.findall("sample")
        sampleof = el.get("sampleof") or (name if samples else "")
        games[name] = {
            "name": name,
            "description": clean(el.findtext("description")),
            "year": clean(el.findtext("year")),
            "manufacturer": clean(el.findtext("manufacturer")),
            "cloneof": el.get("cloneof") or "",
            "romof": el.get("romof") or "",
            "sampleof": sampleof,
            "needsSamples": 1 if samples else 0,
            "disks": len(el.findall("disk")),
            "runnable": 0 if (el.get("isbios") == "yes" or el.get("runnable") == "no") else 1,
            "roms": roms,
        }
        order.append(name)
        el.clear()

    # A BIOS set is a romof target that is not the game's parent (bldyror2 romof=psarc95, cloneof="") or isbios="yes".
    bios_sets = {g["romof"] for g in games.values() if g["romof"] and g["romof"] != g["cloneof"]}
    bios_sets |= {g["name"] for g in games.values() if g["runnable"] == 0}

    def bios_for(g):
        cur = g["romof"]
        seen = set()
        while cur and cur not in seen:
            seen.add(cur)
            if cur in bios_sets:
                return cur
            cur = games.get(cur, {}).get("romof", "")
        return ""

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    rom_count = 0
    with gzip.open(OUT, "wt", encoding="utf-8", compresslevel=9, newline="\n") as f:
        f.write("# generated by cores/mame2010/gen-romdb.py from metadata/mame2010.xml (MAME 0.139)\n")
        f.write("# name\tdescription\tcloneof\tromof\tbios\tsampleof\tneedsSamples\tdisks\trunnable\troms\n")
        for name in order:
            g = games[name]
            rom_count += len(g["roms"])
            f.write("\t".join([
                g["name"], g["description"], g["cloneof"], g["romof"], bios_for(g), g["sampleof"],
                str(g["needsSamples"]), str(g["disks"]), str(g["runnable"]), ";".join(g["roms"]),
            ]) + "\n")
    with open(TITLES, "w", encoding="utf-8", newline="\n") as f:
        for name in order:
            g = games[name]
            f.write("\t".join([g["name"], g["description"], g["year"], g["manufacturer"]]) + "\n")

    size = os.path.getsize(OUT)
    missing_bios = sorted(b for b in bios_sets if b not in games)
    print(f"{len(games)} games, {rom_count} roms ({skipped_optional} optional skipped), {len(bios_sets)} bios sets")
    print(f"-> {OUT} ({size / 1024:.0f} KB gzipped), {TITLES} ({os.path.getsize(TITLES) / 1024:.0f} KB)")
    if missing_bios:
        print(f"note: bios sets referenced but absent from the DAT: {missing_bios}")
    return 0 if size < MAX_BYTES else 1


if __name__ == "__main__":
    sys.exit(main())
